# Generated by Django 6.0.6 on 2026-06-29 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 6, 29, 10, 28, 33, 728737)
            ),
        ),
    ]
