# Generated by Django 6.0.6 on 2026-06-30 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 6, 30, 10, 40, 33, 614430)
            ),
        ),
    ]
