# Generated by Django 6.0.6 on 2026-06-30 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 6, 30, 11, 10, 32, 602767)
            ),
        ),
    ]
