# Generated by Django 6.0.6 on 2026-07-02 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 7, 2, 9, 33, 30, 166590)
            ),
        ),
    ]
