# Generated by Django 6.0.6 on 2026-07-02 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 7, 2, 10, 33, 53, 393167)
            ),
        ),
    ]
