# Generated by Django 6.0.6 on 2026-07-04 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 7, 4, 10, 56, 4, 969035)
            ),
        ),
    ]
