# Generated by Django 6.0.6 on 2026-07-26 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_brand_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2026, 7, 26, 15, 12, 36, 846184)
            ),
        ),
    ]
