# Generated by Django 4.2 on 2026-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0030_alter_brand_id_alter_category_id_alter_inventory_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
