# Generated by Django 4.2 on 2026-09-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0033_attribute_categoryattribute_attributeoption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="shop.attribute",
                    ),
                ),
                (
                    "multiple_option",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multiple_product_values",
                        to="shop.attributeoption",
                    ),
                ),
                (
                    "option_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_values",
                        to="shop.attributeoption",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"), name="unique_product_attribute"
            ),
        ),
    ]
