# Generated by Django 4.2 on 2026-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_productvariant_productvariantattribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="combination_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "combination_key"),
                name="unique_product_variant_combination",
            ),
        ),
    ]
