# Generated by Django 6.0.6 on 2026-06-29 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingAdress",
            new_name="ShippingAddress",
        ),
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "ShippingAddress"},
        ),
    ]
