# Generated by Django 6.0.6 on 2026-06-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_shippingadress_shippingaddress_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Shipping Address"},
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="adress1",
            new_name="shipping_adress1",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="email",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="full_name",
            new_name="shipping_full_name",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="phone",
            new_name="shipping_phone",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="adress2",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="state",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_adress2",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="shipping_zipcode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
