# Generated by Django 6.0.6 on 2026-06-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="shipping_phone",
        ),
    ]
