# Generated by Django 6.0.6 on 2026-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "در انتظار پرداخت"),
                    ("Processing", "در حال پردازش"),
                    ("Shipping", "ارسال به پست"),
                    ("Delivred", "ارسال شده"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
