# Generated by Django 6.0.6 on 2026-07-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="products",
            new_name="product",
        ),
    ]
