# Generated by Django 6.0.6 on 2026-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_rename_products_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_adress",
            field=models.TextField(max_length=150000),
        ),
    ]
